project:
  type: website

website:
  title: "TechFeed"
  sidebar:
    contents:
      - href: index.qmd
        text: Home

format:
  html:
    theme: styles.scss
    mainfont: Archivo
    toc: true



